### ISSUE TITLE
Issue in the Similar_kozak function of the FunUV_annotation.py

### ISSUE THREAD

**Issue by rjcpinto** [Wangxiaoyue-lab/FunUV#1]
Hello,

I am using FunUV to analyze a set of over 200 5'UTR somatic mutations.

When I run Sub_MutSeqByMANE.py, only 188 out of the 262 mutations are retrieved.

Subsequently, when I run FunUV_annotation.py, some variants are successfully annotated; however, the script encounters an error with certain specific mutations:

```
sh: 1: tomtom: not found
Traceback (most recent call last):
  File "path/to/FunUV_annotation.py", line 655, in <module>
    main()
  File "path/to/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "path/to/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "path/to/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "path/to/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "path/to/FunUV_annotation.py", line 64, in main
    kozak_score = Score_kozak(var, pos, subseq2, ref, alt, kozakfile)
  File "path/to/FunUV_annotation.py", line 258, in Score_kozak
    kzk_score = Similar_kozak(var+'_'+pos+"_ref", var+'_'+pos+"_alt", vartomfile)
  File "path/to/FunUV_annotation.py", line 284, in Similar_kozak
    with open(tfile) as tf:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_vartom_out/tomtom.tsv'
```

This is the tmp_vartom.txt file for one of the mutations causing the error:

```
MEME version 4

ALPHABET= ACGT

Background letter frequencies (from uniform background):

A 0.25000 C 0.25000 G 0.25000 T 0.25000

MOTIF MRPS15_chr1_36464377_A_G_5UTR_7_ref_1 1

letter-probability matrix: alength= 4 w= 8 nsites= 20 E= 0

0.0	1.0	0.0	0.0
0.0	0.0	1.0	0.0
1.0	0.0	0.0	0.0
1.0	0.0	0.0	0.0
0.0	0.0	0.0	1.0
0.0	0.0	1.0	0.0
0.0	0.0	1.0	0.0
0.0	0.0	0.0	1.0
```

Do you know what can be causing this?

Best regards

**Comment by guangyu1990** [comment]
Hi,

Thanks for reaching out! Here are some details regarding your questions:

1.Issue with Sub_MutSeqByMANE.py Output:
This is likely because some of the input sites are not annotated as UTR sites in the MANE recommended transcripts, which leads to their exclusion. To resolve this issue, you have two options:

Option 1: Modify or reconstruct the GFF file (MANE.GRCh38.v1.1.ensembl_genomic.gff.gz) to include the transcript information where the site is annotated as UTR and rerun Sub_MutSeqByMANE.py.
Option 2: Extract sequences of 50 bp upstream and downstream of the input variant positions and format them according to the *addseq.txt example provided.


2.Issue with Tomtom Module Path:
It looks like there is a problem finding the Tomtom module. Please ensure that MEME version 5.3.3 is installed and that its path is added to your environment variables. This will allow you to directly access the Tomtom module.

Feel free to reach out if you need further assistance!

Best regards

**Comment by rjcpinto** [comment]
Hello,

Thanks for the solutions. They worked perfectly, and the issues are all sorted now.

Best regards
